[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
authors = ["Seismic Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/SeismicSystems/seismic-alloy"
repository = "https://github.com/SeismicSystems/seismic-alloy"
exclude = ["benches/", "tests/"]

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "warn"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
# Workspace
seismic-alloy-consensus = { version = "0.0.1", path = "crates/consensus", default-features = false }
seismic-alloy-rpc-types = { version = "0.0.1", path = "crates/rpc-types", default-features = false }
seismic-alloy-network = { version = "0.0.1", path = "crates/network", default-features = false }
seismic-alloy-provider = { version = "0.0.1", path = "crates/provider", default-features = false }
seismic-prelude = { version = "0.0.1", path = "crates/prelude" }

seismic-enclave = "0.1.0"

revm = { version = "29.0.0", default-features = false }
seismic-revm = "1.0.0"

# Alloy
alloy-consensus = { version = "=1.1.0", default-features = false }
alloy-eips = { version = "=1.1.0", default-features = false }
alloy-network = { version = "=1.1.0", default-features = false }
alloy-network-primitives = { version = "=1.1.0", default-features = false }
alloy-node-bindings = { version = "=1.1.0", default-features = false }
alloy-provider = { version = "=1.1.0", features = [
    "reqwest",
    "ws",
    "trace-api",
] }
alloy-pubsub = { version = "=1.1.0", default-features = false }
alloy-rpc-types-eth = { version = "=1.1.0", default-features = false }
alloy-rpc-types-engine = { version = "=1.1.0", default-features = false }
alloy-rpc-client = { version = "=1.1.0", default-features = false }
alloy-rpc-types = { version = "=1.1.0", default-features = false }
alloy-serde = { version = "=1.1.0", default-features = false }
alloy-signer = { version = "=1.1.0", default-features = false }
alloy-signer-local = { version = "=1.1.0", default-features = false }
alloy-contract = { version = "=1.1.0", default-features = false }
alloy-transport = { version = "=1.1.0", default-features = false }
alloy-genesis = { version = "=1.1.0", default-features = false }

# Alloy RLP
alloy-rlp = { version = "0.3.12", default-features = false }
alloy-eip7702 = { version = "0.6.1", default-features = false }

# Alloy Core
alloy-primitives = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-json-abi = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-sol-macro-expander = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-sol-macro-input = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-sol-types = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-sol-type-parser = { version = "1.3.1", default-features = false, features = ["seismic"] }
alloy-dyn-abi = { version = "1.3.1", default-features = false, features = ["seismic"] }

alloy-trie = { version = "0.9.1", default-features = false }

# Serde
serde_repr = "0.1"
serde = { version = "1.0.226", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_with = "3.11"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# Encoding
snap = "1.1.1"
bincode = "1.3.3"
ethereum_ssz = "0.8"

# rpc
jsonrpsee = { version = "0.24", features = [
    "jsonrpsee-core",
    "client-core",
    "server-core",
    "macros",
] }
jsonrpsee-core = "0.24"
jsonrpsee-types = "0.24"

# misc
async-trait = "0.1.85"
bytes = { version = "1.5", default-features = false }
cfg-if = "1"
derive_more = { version = "1.0", default-features = false }
futures = "0.3"
futures-util = "0.3"
lazy_static = { version = "1.5.0", default-features = false }
reqwest = { version = "0.12", default-features = false }
spin = { version = "0.9.8", features = ["mutex"] }
similar-asserts = "1.6"
thiserror = { version = "2.0", default-features = false }
unsigned-varint = "0.8.0"

# tracing
tracing-subscriber = "0.3.19"
tracing = { version = "0.1.41", default-features = false }

## misc-testing
arbitrary = { version = "1.4", features = ["derive"] }
arbtest = "0.3"
rand = "0.8"
proptest = "1.6"
proptest-derive = "0.5"
tokio = "1"
rstest = "0.24.0"
secp256k1 = { version = "0.30" }

## crypto
c-kzg = { version = "2.1.1", default-features = false }
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }

[patch.crates-io]
# Seismic enclave
seismic-enclave =  { git = "https://github.com/SeismicSystems/enclave.git", rev = "ac5e28dac1ee8ec0e3922b010e6da072d6e784aa" }

# seismic-alloy-core
alloy-dyn-abi = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-primitives = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-json-abi = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-sol-macro-expander = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-sol-macro-input = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-sol-types = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }
alloy-sol-type-parser = { git = "https://github.com/SeismicSystems/seismic-alloy-core.git", rev = "e1a9cd00d657dc7b6aca175025cc4ac4053dd094" }

alloy-trie = { git = "https://github.com/SeismicSystems/seismic-trie.git", rev = "d8425918ced1d62043c3a64b382d6fa1d8c25518" }

alloy-consensus = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
alloy-eips = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
alloy-serde = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
alloy-network-primitives = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }

# alloy-network = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-consensus-any = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-rpc-types-any = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-rpc-types-eth = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-signer = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-provider = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-transport = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-pubsub = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-signer-local = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }
# alloy-genesis = { git = "https://github.com/alloy-rs/alloy", tag = "v1.1.0" }

# revm
# Temporarily pointing to veridise-audit-feb-2026 branch. Will point back to seismic after the audit is complete.
revm = { git = "https://github.com/SeismicSystems/seismic-revm.git", rev = "5ba06828ab6f0f8d0d62d745efd8a35862f8603c" }
seismic-revm = { git = "https://github.com/SeismicSystems/seismic-revm.git", rev = "5ba06828ab6f0f8d0d62d745efd8a35862f8603c" }
