[package]
name = "seismic-alloy-provider"
description = "Interface with a Seismic blockchain"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-client = { workspace = true, features = ["reqwest"] }
alloy-transport.workspace = true
alloy-sol-types.workspace = true

seismic-alloy-consensus.workspace = true
seismic-alloy-network.workspace = true
seismic-enclave-crypto.workspace = true

async-trait.workspace = true
reqwest.workspace = true


[dev-dependencies]
tokio.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-signer-local.workspace = true
alloy-node-bindings = { workspace = true }
alloy-provider = { workspace = true, features = ["anvil-api"] }
seismic-alloy-rpc-types.workspace = true
alloy-pubsub.workspace = true
futures-util.workspace = true
futures.workspace = true
